info:
  name: Listar configurações municipais
  type: http
  seq: 1
  tags:
    - Informações fiscais

http:
  method: GET
  url: "{{baseUrl}}/v3/fiscalInfo/municipalOptions"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Ok
    request:
      url: "{{baseUrl}}/v3/fiscalInfo/municipalOptions"
      method: GET
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "authenticationType": "CERTIFICATE",
            "supportsCancellation": true,
            "usesSpecialTaxRegimes": true,
            "usesServiceListItem": true,
            "specialTaxRegimesList": [
              {
                "label": "Microempresa Municipal",
                "value": "1"
              }
            ],
            "nationalPortalTaxCalculationRegimeList": [
              {
                "label": "Regime de apuração dos tributos federais e municipal pelo SN",
                "value": "0"
              }
            ],
            "nationalPortalTaxCalculationRegimeHelp": "Isso identifica o regime de apuração tributária pelo Simples Nacional de sua empresa, se desejar deixar sem nenhuma opção marcada selecione a opção \"Nenhum\". Deve ser preenchido somente por empresas enquadradas como ME ou EPP optantes do Simples Nacional. Consulte a necessidade desta informação com a sua prefeitura ou a sua contabilidade.",
            "municipalInscriptionHelp": "Informe somente os números sem ponto nem formatação (se contiver letras, insira sempre em maiúscula).\r\n\r\nExemplos válidos: 4301000010 ou 131436001X",
            "specialTaxRegimeHelp": "Isso identifica o regime de tributação de sua empresa, se desejar deixar sem nenhuma opção marcada selecione o traço (\"-\").\r\n \r\n Empresas do simples nacional geralmente optam pelo ME ou ME EPP",
            "serviceListItemHelp": "Informe aqui o item da lista de serviço, é também um identificador do serviço prestado.\r\n \r\n Você precisa preencher o item da lista de serviço mantendo a formatação.\r\n Exemplos válidos: 17.02 ou 8.02",
            "digitalCertificatedHelp": "Sua prefeitura exige a utilização de certificado digital, portanto, inclua aqui o arquivo de seu certificado A1.",
            "accessTokenHelp": null,
            "municipalServiceCodeHelp": "Informe aqui o código municipal que identifica o serviço prestado na nota fiscal. \r\nEm algumas cidades esse código é conhecido como código de tributação ou CTISS.\r\n\r\nExemplo válido: 010300388"
          }
  - name: 400 Response
    description: Bad Request
    request:
      url: "{{baseUrl}}/v3/fiscalInfo/municipalOptions"
      method: GET
    response:
      status: 400
      statusText: Bad Request
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "errors": [
              {
                "code": "error_code",
                "description": "Descrição do erro"
              }
            ]
          }
  - name: 401 Response
    description: Unauthorized
    request:
      url: "{{baseUrl}}/v3/fiscalInfo/municipalOptions"
      method: GET
    response:
      status: 401
      statusText: Unauthorized
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "errors": [
              {
                "code": "invalid_access_token",
                "description": "A chave de API fornecida é inválida"
              }
            ]
          }
  - name: 403 Response
    description: Forbidden. Ocorre quando o body da requisição está preenchido, chamadas de método GET precisam ter um body vazio.
    request:
      url: "{{baseUrl}}/v3/fiscalInfo/municipalOptions"
      method: GET
    response:
      status: 403
      statusText: Forbidden
      body:
        type: text
        data: ""
